language: php
sudo: false
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - 7.1
  - 7.2
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
before_script:
  - composer create-project bearsaturday/skeleton bear
  - cd bear
script:
  - ./vendor/bin/phpunit
